# Don't re-download node_modules every time. Cache it
cache:
  paths:
    - node_modules/

validate:
  script:
    - eclint check "**/*.html" "**/*.js" "**/*.css" "**/*.md"
    - yarn install
    - npm run lint
    - npm test

deploy:
  script: deploy
  only: [master, dev, /^dev-.*$/]
  variables:
    SERVER: gramener.com
    URL: comicgen
    VERSION: static
    SETUP: yarn install && npm run build
